### ISSUE TITLE
[!] Country code JP not in server list

### ISSUE THREAD

**Issue by zhuanshulz** [ruped24/autovpn2#1]
I try to use the command 
"sudo autovpn2 JP"
to connect a random vpn server, but it echoed "[!] Country code JP not in server list", so it didn;t connect a server successfully. And i do not know how to solve it.

**Comment by ruped24** [comment]
> I try to use the command
> "sudo autovpn2 JP"
> to connect a random vpn server, but it echoed "[!] Country code JP not in server list", so it didn;t connect a server successfully. And i do not know how to solve it.

 Hit the up arrow key to retry a few times, It _will_ connect.  

Here are a few other countries to try:

- jp
-  **kr**
- vn
- th

You can get the list from [here](https://www.vpngate.net/en/). 
Countries on the left are available.

Another country should solve the problem...

**Comment by zhuanshulz** [comment]
fine, thanks a lot!

**Comment by ruped24** [comment]
> fine, thanks a lot!

**Comment by ruped24** [comment]
> > fine, thanks a lot!

No problem. You're welcome
